platform: linux
image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cargo-lambda/cargo-lambda
inputs:
  - name: code
outputs:
  - name: artifacts
run:
  path: sh
  args: 
  - -exc
  - |
    /usr/local/bin/build.sh
    exit 1

