platform: linux
image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cargo-lambda:1.0.0
inputs:
  - name: code
outputs:
  - name: artifacts
run:
  path: sh
  args: 
  - -exc
  - |
    /usr/local/bin/build.sh
    exit 1

