platform: linux
image_resource:
  type: registry-image
  source:
    repository: calavera/cargo-lambda
inputs:
  - name: code
outputs:
  - name: artifacts
run:
  path: sh
  args: 
  - -exc
  - |
    cd code/lambda
    cargo lambda build --release --output-format zip
    mv target/lambda/fakeS3Upload/bootstrap.zip ../../artifacts/
