platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
inputs:
  - name: artifacts
  - name: code
run:
  path: sh
  args:
    - exc
    - |
     cd code
     terraform init
     terraform apply -var='region=$REGION' -var='environment=$ENV' -var='path_to_zip=../artifacts'

