
platform: linux
image_resource:
  type: registry-image
  source:
    repository: hashicorp/terraform
inputs:
  - name: code
run:
  path: sh
  args:
    - -c
    - |
     cd code
     terraform init
     terraform  -var="region=$REGION" -var="environment=$ENV" -auto-approve
