resource_types:
  - name: registry-image
    type: registry-image
    source:
      repository: concourse/registry-image-resource
      tag: latest
resources:
  - name: image-upload-lambda
    type: git
    icon: github-circle
    source:
      branch: main
      uri: https://github.com/Spheny1/JasperHealth-Takehome-assesment.git
jobs:
  - name: build-and-deploy-lambda
    plan:
      - get: image-upload-lambda
        trigger: true
      - task: build-artifact
        file: image-upload-lambda/ci/tasks/cargo-lambda-build.yaml
        input_mapping:
          code: image-upload-lambda
      - task: deploy-with-terraform
        file: image-upload-lambda/ci/tasks/deploy-lambda.yaml
        input_mapping:
          artifact: artifacts
          code: image-upload-lambda
        params:
          #DO NOT CHECK THIS IN WITH VALUES
          AWS_ACCESS_KEY_ID: abcd
          AWS_SECRET_ACCESS_KEY: efgh


